routes/web.php
<?php

use App\Http\Controllers\AlbumsController;
use App\Http\Controllers\ShareController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeletedIncomingLettersController;
use App\Http\Controllers\DeletedOngoingLettersController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IncomingLetterController;
use App\Http\Controllers\LogLettersController;
use App\Http\Controllers\OngoingLetterController;
use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['register' => false]);

Route::middleware('auth')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::put('profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::get('profile/logout', [ProfileController::class, 'logout'])->name('profile.logout');

    Route::resource('users', UsersController::class)->except(['show']);

    Route::resource('albums', AlbumsController::class);

    Route::get('albums/share/file/{file_id}', [ShareController::class, 'shareFile'])->name('albums.share.file');
    Route::post('albums/share/file/{file_id}', [ShareController::class, 'createShareFile'])->name('albums.share.file.create');
    Route::delete('albums/share/file/{share_id}', [ShareController::class, 'destroyShareFile'])->name('albums.share.file.destroy');

    Route::get('albums/share/album/{album_id}', [ShareController::class, 'shareAlbum'])->name('albums.share.album');
    Route::post('albums/share/album/{album_id}', [ShareController::class, 'createShareAlbum'])->name('albums.share.album.create');
    Route::delete('albums/share/album/{share_id}', [ShareController::class, 'destroyShareAlbum'])->name('albums.share.album.destroy');

    Route::get('albums/file/{id}', [AlbumsController::class, 'getFile'])->name('albums.file');
    Route::delete('albums/{id}/file/{file_id}', [AlbumsController::class, 'destroyFile'])->name('albums.destroy.file');
    Route::post('albums/{id}', [AlbumsController::class, 'upload'])->name('albums.upload');

    Route::get('roles/toggle-sync-permission/{role_id}/{permission_id}', [RolesController::class, 'toggleSyncPermission'])->name('roles.toggle.sync.permission');
    Route::resource('roles', RolesController::class)->except(['show']);
    // Route::resource('permissions', PermissionsController::class)->except(['show']);
});

Route::get('share/file/{token}', [ShareController::class, 'sharedFile'])->name('share.file');
Route::get('share/album/{token}', [ShareController::class, 'sharedAlbum'])->name('share.album');
Route::get('share/album/{token}/{id}', [ShareController::class, 'fileFromSharedAlbum'])->name('share.album.file');

app/Models/Album.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphMany;

class Album extends Model
{
    protected $fillable = [
        'title',
        'description',
    ];

    public function media() : MorphMany
    {
        return $this->morphMany(Media::class, 'media_able');
    }

    public function shares()
    {
        return $this->morphMany(Share::class, 'shareable');
    }

    public function humanSize()
    {
        $size = $this->sizes;
        $precision = 1;
        $units = array('B','kB','MB','GB','TB','PB','EB','ZB','YB');
        $step = 1024;
        $i = 0;
        while (($size / $step) > 0.9) {
            $size = $size / $step;
            $i++;
        }
        return round($size, $precision).$units[$i];
    }
}

app/Http/Controllers/AlbumsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Album;
use App\Models\Media;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;

class AlbumsController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:baca album')->only(['index', 'show']);
        $this->middleware('can:buat album')->only(['create', 'store']);
        $this->middleware('can:edit album')->only(['edit', 'update', 'upload', 'destroyFile', 'getFile']);
        $this->middleware(['can:hapus album', 'password.confirm'])->only('destroy');
    }

    public function index(Request $request)
    {
        if (!empty($request->input('search'))) {
            $search = '%' . $request->input('search') . '%';
            $albums = Album::where('title', 'like', $search);
            $albums->orWhere('description', 'like', $search);
        } else {
            $albums = Album::orderBy('id', 'desc');
        }
        $albums = $albums
            ->withCount(['media', 'media as sizes'=>function($q){
                $q->select(DB::raw('SUM(size)'));
            }])
            ->paginate(20)
            ->appends(['search' => $request->input('search')]);
        return view('albums.index', ['albums' => $albums]);
    }

    public function create()
    {
        return view('albums.create');
    }

    public function store(Request $request)
    {
        $data = $request->validate([
            'title' => ['required', 'string', 'max:255'],
            'description' => ['required', 'string', 'max:500']
        ]);
        $album = Album::create($data);
        return redirect()->route('albums.show', $album->id)->withSuccess('Album berhasil dibuat.');
    }

    public function show($id)
    {
        $album = Album::with(['media' => function($q){
            $q->orderBy('created_at', 'desc');
        }])->findOrFail($id);
        return view('albums.show', ['album' => $album]);
    }

    public function edit($id)
    {
        $album = Album::findOrFail($id);
        return view('albums.edit', ['album' => $album]);
    }

    public function update(Request $request, $id)
    {
        $album = Album::findOrFail($id);
        $data = $request->validate([
            'title' => ['required', 'string', 'max:255'],
            'description' => ['required', 'string', 'max:500']
        ]);
        $album->update($data);
        return redirect()->back()->withSuccess('Album berhasil diedit.');
    }

    public function destroy($id)
    {
        $album = Album::findOrFail($id);
        foreach($album->media as $media) {
            $media->destroyFile();
            $media->shares()->delete();
            $media->delete();
        }
        $album->shares()->delete();
        $album->delete();
        return redirect()->route('albums.index')->withSuccess('Album telah dihapus');
    }

    public function upload(Request $request, $id)
    {
        $album = Album::findOrFail($id);
        $data = $request->validate(['file' => 'required|mimes:jpeg,jpg,png,flv,mp4,mov,avi|max:10000000']);

        $mime = $data['file']->getMimeType();
        $ext = explode('/', $mime)[1];
        $type = explode('/', $mime)[0];
        $size = $data['file']->getSize();

        $name = $album->id . '/' . now()->timestamp . Str::random(20) . '.' . $ext;
        $data['file']->storeAs('albums', $name);
        $media = new Media([
            'name' => $name,
            'original_name' => $data['file']->getClientOriginalName(),
            'type' => $type,
            'size' => $size,
        ]);
        $album->media()->save($media);
        if($type == 'video') {
            Media::createVideoThumb($data['file'], $name);
        } else {
            Media::createImageThumb($data['file'], $name);
        }
        $album->touch();
    }

    public function getFile($id)
    {
        $media = Media::findOrFail($id);
        $name = 'albums/' . $media->name;
        abort_unless(Storage::exists($name), 404);
        return Storage::response($name, $media->original_name);
    }

    public function destroyFile($id, $file_id)
    {
        $album = Album::findOrFail($id);
        $media = Media::findOrFail($file_id);
        $media->destroyFile();
        $media->shares()->delete();
        $media->delete();
        $album->touch();
        return redirect()->back()->withSuccess('File telah dihapus');
    }
}

resources/views/albums/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
  <div class="panel panel-bordered">
    <div class="panel-heading">
      <h3 class="panel-title">Buat Album</h3>
      <div class="panel-actions">
        <a href="#" onclick="history.back()" class="btn btn-danger btn-sm">Kembali</a>
      </div>
    </div>
    <div class="panel-body">
      <form action="{{ route('albums.store') }}" method="POST">
        @csrf
        <div class="form-group">
          <label for="title">Judul</label>
          <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" placeholder="Judul..." value="{{ old('title') }}">
          @error('title')
            <span class="invalid-feedback">{{ $message }}</span>
          @enderror
        </div>
        <div class="form-group">
          <label for="description">Deskripsi</label>
          <textarea class="form-control @error('description') is-invalid @enderror" name="description" placeholder="Deskripsi...">{{ old('description') }}</textarea>
          @error('description')
            <span class="invalid-feedback">{{ $message }}</span>
          @enderror
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Buat Album</button>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/albums/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
  <div class="panel panel-bordered">
    <div class="panel-heading">
      <h3 class="panel-title">Edit Album</h3>
      <div class="panel-actions">
        <a href="#" onclick="history.back()" class="btn btn-danger btn-sm">Kembali</a>
      </div>
    </div>
    <div class="panel-body">
      <form action="{{ route('albums.update', $album->id) }}" method="POST">
        @csrf
        @method('put')
        <div class="form-group">
          <label for="title">Judul</label>
          <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" placeholder="Judul..." value="{{ $album->title }}">
          @error('title')
            <span class="invalid-feedback">{{ $message }}</span>
          @enderror
        </div>
        <div class="form-group">
          <label for="description">Deskripsi</label>
          <textarea class="form-control @error('description') is-invalid @enderror" name="description" placeholder="Deskripsi...">{{ $album->description }}</textarea>
          @error('description')
            <span class="invalid-feedback">{{ $message }}</span>
          @enderror
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Edit Album</button>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/albums/index.blade.php
@extends('layouts.app')



@section('content')
  <div class="container-fluid">
    <div class="panel panel-bordered">
      <div class="panel-heading">
        <h3 class="panel-title">Daftar Album</h3>
        <div class="panel-actions">
          @can('buat album')
            <a href="{{ route('albums.create') }}" class="btn btn-sm btn-primary">Buat Album</a>
          @endcan
        </div>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <form method="get" class="input-group">
          <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request()->input('search') }}">
            <span class="input-group-btn">
              <button type="submit" class="btn btn-primary"><i class="icon wb-search" aria-hidden="true"></i></button>
            </span>
          </form>
        </div>
      </div>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Judul</th>
              <th>Total file</th>
              <th>Ukuran</th>
              <th>Terakhir diubah</th>
              <th class="text-center" style="width: 140px;">Aksi</th>
            </tr>
          </thead>
          <tbody>
            @foreach($albums as $album)
            <tr ondblclick="location.href = '{{ route('albums.show', $album->id) }}'">
              <td class="align-middle">{{ $album->title }}</td>
              <td class="align-middle">{{ $album->media_count }}</td>
              <td class="align-middle">{{ $album->humanSize() }}</td>
              <td  class="align-middle">{{ $album->updated_at->isoFormat('D MMMM YYYY') }}</td>
              <td class="text-center py-0 align-middle">
                <a href="{{ route('albums.show', $album->id) }}" class="btn btn-outline-default btn-sm btn-icon" title="Edit Pengguna"><i class="wb-eye"></i></a>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
      <div class="panel-footer">
        {{ $albums->links() }}
      </div>
    </div>
  </div>
@endsection

resources/views/albums/share.blade.php
@extends('layouts.app')

@section('script:after')
@endsection

@section('content')
  <div class="container-fluid">
    <div class="panel panel-bordered">
      <div class="panel-heading">
        <h3 class="panel-title">Share {{ $type }}</h3>
        <div class="panel-actions">
          <a href="#" onclick="history.back()" class="btn btn-danger btn-sm">Kembali</a>
        </div>
      </div>
      <div class="panel-body">
        <h4>@if($type=='file') {{ $media->original_name }} @else {{ $album->title }} @endif</h4>
        <form method="post" action="{{ route('albums.share.'. $type, $type == 'file' ? $media->id : $album->id) }}">
          @csrf
          <div class="form-group">
            <label for="name">Nama</label>
            <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" placeholder="Nama..." value="{{ old('name') }}">
            @error('name')
              <span class="invalid-feedback">{{ $message }}</span>
            @enderror
          </div>
          <div class="form-group">
            <label for="hours">Waktu Kadaluarsa (jam)</label>
            <input type="number" class="form-control @error('hours') is-invalid @enderror" name="hours" placeholder="Waktu Kadaluarsa (jam)..." value="{{ old('hours') }}">
            @error('hours')
              <span class="invalid-feedback">{{ $message }}</span>
            @enderror
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary">Buat link</button>
          </div>
        </form>
      </div>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>nama</th>
              <th>url</th>
              <th>Kadaluarsa</th>
              <th class="text-center" style="width: 140px;">Aksi</th>
            </tr>
          </thead>
          <tbody>
            @php
              if($type == 'file'){
                $shares = $media->shares;
              } else {
                $shares = $album->shares;
              }
            @endphp
            @foreach($shares as $share)
            <tr>
              <td class="align-middle">{{ $share->name }}</td>
              <td class="align-middle"><a href="{{ route('share.' . $type, $share->token) }}" target="_blank">{{ route('share.' . $type, $share->token) }}</a></td>
              <td class="align-middle">
                @if ($share->expired_at > now())
                {{ $share->expired_at->diffForHumans() }}
                @elseif($share->expired_at === null)
                Tak berwaktu
                @else
                Kadaluarsa
                @endif
              </td>
              <td class="text-center py-0 align-middle">
                <button href="#" class="btn btn-outline-default btn-xs" v-clipboard="'{{ route('share.' . $type, $share->token) }}'">Copy</button>
                <button class="btn btn-outline-danger btn-xs" v-delete-confirm:form-delete-share-{{ $share->id }}>Hapus</button>
                <form action="{{ route('albums.share.' . $type, $share->id) }}" method="post" id="form-delete-share-{{ $share->id }}">
                  @csrf
                  @method('delete')
                </form>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
@endsection

resources/views/albums/show.blade.php
@extends('layouts.app')
@section('style:after')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
@endsection
@section('script:after')
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>

@endsection
@section('content')
  <div class="container-fluid">
    <div class="panel panel-bordered">
      <div class="panel-heading">
        <h3 class="panel-title">{{ $album->title }}</h3>
        <div class="panel-actions">
          @can('edit album')
          <a href="{{ route('albums.edit', $album->id) }}" class="btn btn-sm btn-primary">Edit</a>
          @endcan
          @can('share file')
          <a href="{{ route('albums.share.album', $album->id) }}" class="btn btn-sm btn-primary">Share</a>
          @endcan
          @can('hapus album')
          <button class="btn btn-danger btn-sm" v-delete-confirm:form-delete-album>Hapus</button>
          <form action="{{ route('albums.destroy', $album->id) }}" method="post" id="form-delete-album">
            @csrf
            @method('delete')
          </form>
          @endcan
        </div>
      </div>
      <div class="panel-body">
        <p class="m-0 small font-weight-bold">Terakhir diubah {{ $album->updated_at->isoFormat('D MMMM YYYY') }}</p>
        <p>{{ $album->description }}</p>
      </div>
    </div>
    @can('edit album')
    <media-uploader class="mb-3" upload-url="{{ route('albums.upload', $album->id) }}" ></media-uploader>
    @endcan
    <div class="row">
      @foreach ($album->media as $media)
        <div class="col-lg-2 col-md-3 col-sm-4">
          <media-list size="{{ $media->humanSize() }}" thumb="/storage/thumb/{{ $media->name }}.jpeg" media="{{ route('albums.file', $media->id) }}" original_name="{{ $media->original_name }}" @if($media->type == 'video') video @endif>
            <a href="{{ route('albums.file', $media->id) }}" download class="btn btn-primary btn-xs btn-block">Download</a>
            @can('share file')
              <a href="{{ route('albums.share.file', $media->id) }}" class="btn btn-primary btn-xs btn-block">Share</a>
            @endif
            @can('edit album')
              <button class="btn btn-danger btn-xs btn-block" v-delete-confirm:form-delete-file-{{ $media->id }}>Hapus</button>
              <form action="{{ route('albums.destroy.file', [$album->id, $media->id]) }}" method="post" id="form-delete-file-{{ $media->id }}">
                @csrf
                @method('delete')
              </form>
            @endcan
          </media-list>
        </div>
      @endforeach
    </div>
  </div>
@endsection