routes/web.php
<?php

use App\Http\Controllers\AlbumsController;
use App\Http\Controllers\ShareController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeletedIncomingLettersController;
use App\Http\Controllers\DeletedOngoingLettersController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IncomingLetterController;
use App\Http\Controllers\LogLettersController;
use App\Http\Controllers\OngoingLetterController;
use App\Http\Controllers\PermissionsController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes(['register' => false]);

Route::middleware('auth')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::put('profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::get('profile/logout', [ProfileController::class, 'logout'])->name('profile.logout');

    Route::resource('users', UsersController::class)->except(['show']);

    Route::resource('albums', AlbumsController::class);

    Route::get('albums/share/file/{file_id}', [ShareController::class, 'shareFile'])->name('albums.share.file');
    Route::post('albums/share/file/{file_id}', [ShareController::class, 'createShareFile'])->name('albums.share.file.create');
    Route::delete('albums/share/file/{share_id}', [ShareController::class, 'destroyShareFile'])->name('albums.share.file.destroy');

    Route::get('albums/share/album/{album_id}', [ShareController::class, 'shareAlbum'])->name('albums.share.album');
    Route::post('albums/share/album/{album_id}', [ShareController::class, 'createShareAlbum'])->name('albums.share.album.create');
    Route::delete('albums/share/album/{share_id}', [ShareController::class, 'destroyShareAlbum'])->name('albums.share.album.destroy');

    Route::get('albums/file/{id}', [AlbumsController::class, 'getFile'])->name('albums.file');
    Route::delete('albums/{id}/file/{file_id}', [AlbumsController::class, 'destroyFile'])->name('albums.destroy.file');
    Route::post('albums/{id}', [AlbumsController::class, 'upload'])->name('albums.upload');

    Route::get('roles/toggle-sync-permission/{role_id}/{permission_id}', [RolesController::class, 'toggleSyncPermission'])->name('roles.toggle.sync.permission');
    Route::resource('roles', RolesController::class)->except(['show']);
    // Route::resource('permissions', PermissionsController::class)->except(['show']);
});

Route::get('share/file/{token}', [ShareController::class, 'sharedFile'])->name('share.file');
Route::get('share/album/{token}', [ShareController::class, 'sharedAlbum'])->name('share.album');
Route::get('share/album/{token}/{id}', [ShareController::class, 'fileFromSharedAlbum'])->name('share.album.file');

app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RolesController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:mengelola peran');
    }

    public function index()
    {
        return view('roles.index', [ 'roles' => Role::all() ]);
    }

    public function create()
    {
        return view('roles.create');
    }

    public function store(Request $request)
    {
        $tableNames = config('permission.table_names.roles');
        $data = $request->validate(['name' => 'required|string|max:64|min:3|unique:'. $tableNames]);
        Role::create($data);
        return redirect()->route('roles.index')->withSuccess('Peran telah dibuat.');
    }

    public function edit($id)
    {
        $role = Role::where('name', '!=', 'Super Admin')->findOrFail($id);
        $permissions = Permission::all();
        return view('roles.edit', ['role' => $role, 'permissions' => $permissions]);
    }

    public function update(Request $request, $id)
    {
        $role = Role::where('name', '!=', 'Super Admin')->findOrFail($id);
        $tableNames = config('permission.table_names.roles');
        $data = $request->validate(['name' => 'required|string|max:64|min:3|unique:'. $tableNames . ',name,' . $id]);
        $role->update($data);
        return redirect()->back()->withSuccess('Peran telah diedit.');
    }

    public function destroy($id)
    {
        $role = Role::where('name', '!=', 'Super Admin')->findOrFail($id);
        $users = User::role($role->name)->get();
        foreach($users as $user) $user->removeRole($role->name);
        $role->delete();
        return redirect()->route('roles.index')->withSuccess('Peran telah dihapus.');
    }

    public function toggleSyncPermission($role_id, $permission_id)
    {
        $role = Role::where('name', '!=', 'Super Admin')->findOrFail($role_id);
        $permission = Permission::findOrFail($permission_id);

        if($role->hasPermissionTo($permission->name)) {
            $role->revokePermissionTo($permission->name);
        } else {
            $role->givePermissionTo($permission->name);
        }

        return redirect()->back()->withSuccess('Izin peran telah diedit.');
    }
}

resources/views/roles/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="container-fluid">
    <div class="panel panel-bordered">
      <div class="panel-heading">
        <h3 class="panel-title">Buat Peran</h3>
        <div class="panel-actions">
          <a href="{{ route('roles.index') }}" class="btn btn-sm btn-primary">Batal</a>
        </div>
      </div>
      <div class="panel-body">
        <form action="{{ route('roles.store') }}" method="post">
          @csrf
          <div class="form-group">
            <label for="name">Nama</label>
            <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" placeholder="Nama..." value="{{ old('name') }}">
            @error('name')
              <span class="invalid-feedback">{{ $message }}</span>
            @enderror
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary">Buat Peran</button>
          </div>
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="container-fluid">
    <div class="panel panel-bordered">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Peran</h3>
        <div class="panel-actions">
          <a href="{{ route('roles.index') }}" class="btn btn-sm btn-primary">Batal</a>
        </div>
      </div>
      <div class="panel-body">
        <form action="{{ route('roles.update', $role->id) }}" method="post">
          @csrf
          @method('put')
          <div class="form-group">
            <label for="name">Nama</label>
            <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" placeholder="Nama..." value="{{ $role->name }}">
            @error('name')
              <span class="invalid-feedback">{{ $message }}</span>
            @enderror
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary">Edit Peran</button>
          </div>
        </form>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>Nama</th>
            <th class="text-center" style="width: 120px;">Aksi</th>
          </tr>
        </thead>
        <tbody>
          @foreach($permissions as $permission)
          <tr>
            <td>{{ $permission->name }}</td>
            <td class="text-center py-0 align-middle">
              @if($role->hasPermissionTo($permission->name))
              <a href="{{ route('roles.toggle.sync.permission', [$role->id, $permission->id]) }}" class="btn btn-sm btn-danger">Cabut Izin</a>
              @else
              <a href="{{ route('roles.toggle.sync.permission', [$role->id, $permission->id]) }}" class="btn btn-sm btn-primary">Beri Izin</a>
              @endif
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container-fluid">
    <div class="panel panel-bordered">
      <div class="panel-heading">
        <h3 class="panel-title">Daftar Peran</h3>
        <div class="panel-actions">
          <a href="{{ route('roles.create') }}" class="btn btn-sm btn-primary">Buat Peran</a>
        </div>
      </div>
      <div class="table-responsive pt-2">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Nama</th>
              <th class="text-center" style="width: 120px;">Aksi</th>
            </tr>
          </thead>
          <tbody>
            @foreach($roles as $role)
            <tr>
              <td class="align-middle">{{ $role->name }}</td>
              <td class="text-center py-0 align-middle">
                @if($role->name !== 'Super Admin')
                  <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-outline-default btn-sm btn-icon" title="Edit Peran">
                    <i class="wb-pencil"></i>
                  </a>
                  <button class="btn btn-danger btn-sm btn-icon" title="Hapus Peran" v-delete-confirm:form-delete-role-{{ $role->id }}>
                    <i class="wb-trash"></i>
                  </button>
                <form action="{{ route('roles.destroy', $role->id) }}" method="post" id="form-delete-role-{{ $role->id }}">
                  @csrf
                  @method('delete')
                </form>
                @endif
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
@endsection